services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    env_file:
      - ./api-gateway/.env

  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    env_file:
      - ./auth-service/.env

  room-service:
    build: ./room-service
    ports:
      - "5000:5000"
    env_file:
      - ./room-service/.env

  payment-service:
    build: ./payment-service
    ports:
      - "6000:6000"
    env_file:
      - ./payment-service/.env
  student-service:
    build: ./student-service
    ports:
      - "7000:7000"
    env_file:
      - ./student-service/.env
  equipment-service:
    build: ./equipment-service
    ports:
      - "8000:8000"
    env_file:
      - ./equipment-service/.env
