services:
  - type: web
    name: auth-service
    env: docker
    docker:
      buildCommand: "docker build -t auth-service ./auth-service"
      startCommand: "npm start"
    plan: free
    region: oregon
    env: node
